name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3点运行（UTC时间）
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/Aethersailor/Custom_OpenClash_Rules.git
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main || echo "Nothing to merge"
      
      - name: Push to your fork
        run: |
          git push origin main
