name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间上午10点运行（UTC+8）
  workflow_dispatch:     # 允许你手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 防止覆盖 token
          fetch-depth: 0              # 拉取完整历史，避免合并冲突

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Aethersailor/Custom_OpenClash_Rules.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Automated sync from upstream"

      - name: Push changes to your repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
